---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Loading and preprocessing the data
if(!file.exists("getdata-projectfiles-UCI HAR Dataset.zip")) {
  temp <- tempfile()
  download.file("http://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip",temp)
  unzip(temp)
  unlink(temp)
}

activity<-read.csv("activity.csv")
head(activity)

## What is mean total number of steps taken per day?
totalStepsByDay<-aggregate(steps~date, activity, sum)
mean_raw<-mean(totalStepsByDay$steps)
mean_raw

## What is the average daily activity pattern?
averageStepsbyInterval[which.max(averageStepsbyInterval[,2]),1]

## Imputing missing values
missingIndex<-is.na(activity[,1])

m<-mean(averageStepsbyInterval$steps)

activity1<-activity
activity1[missingIndex,1]<-m
head(activity1)

## Are there differences in activity patterns between weekdays and weekends?
activity1$date<-as.Date(activity1$date)

activity2<-activity1%>%
  mutate(dayType= ifelse(weekdays(activity1$date)=="Saturday" | weekdays(activity1$date)=="Sunday", "Weekend", "Weekday"))
head(activity2)

averageStepByDayTypeAndInterval<-activity2 %>%
  group_by(dayType, interval) %>%
  summarize(averageStepByDay=sum(steps))

head(averageStepByDayTypeAndInterval)

##Plot Codes
## Histogram of the total number of steps taken each day
hist(totalStepsByDay$steps, xlab="Class of Total Number of Steps per day", ylab="Number of Days", main="Total Number of Steps taken each day")

##Time series plot of the average number of steps taken
averageStepsbyInterval<-aggregate(steps~interval, activity, mean)
with(averageStepsbyInterval, plot(interval, steps, type = "l"))

##Histogram of the total number of steps taken each day after missing values are imputed
totalStepsByDay1<-aggregate(steps~date, activity1, sum)
hist(totalStepsByDay1$steps, xlab="Class of Total Number of Steps per day", ylab="Number of Days", main="Number of Steps taken each day after missing values are imputed")

##Panel plot comparing the average number of steps taken per 5-minute interval across weekdays and weekends
library(lattice)
with(averageStepByDayTypeAndInterval, 
     xyplot(averageStepByDay ~ interval | dayType, 
            type = "l",      
            main = "Total Number of Steps within Intervals by dayType",
            xlab = "Daily Intervals",
            ylab = "Average Number of Steps"))

